var _save = argument0
ini_open(database_file)
database_include_boolean(database_global, "eula", _save)
database_include_string(database_global, "language", _save)
database_include_string(game.app, "nickname", _save)
database_include_int(game.app.render, "mode_fullscreen_web", _save)
database_include_int(game.app.render, "mode_resolution", _save)
database_include_int(game.app.render, "mode_ratio", _save)
database_include_int(game.app.render, "mode_light_hd", _save)
database_include_int(game.app.render, "mode_outline", _save)
database_include_int(game.app.render, "mode_reflex", _save)
database_include_int(game.app.render, "mode_debug", _save)
database_include_int(game.app.render, "mode_font_hd", _save)
database_include_int(game.app.render, "mode_camera", _save)
database_include_int(game.app.render, "mode_auto", _save)
database_include_int(game.app.input, "mode_button", _save)
database_include_int(game.app.audio, "volume", _save)
database_include_int(game.app.audio, "mixer_fx", _save)
database_include_int(game.app.audio, "mixer_music", _save)
database_include_int(game.app.audio, "mixer_voice", _save)
database_include_int(game.app.audio, "mute", _save)
ini_close()